name: Build on main push

on:
  push:
    branches:
      - main

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build stacks-status image
    runs-on: ubuntu-18.04
    env:
      VERSION: 0.0.3
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --build-arg VERSION=$VERSION \
          --tag ${{ secrets.DOCKER_HUB_USER }}/stacks-status:$VERSION \
          --output "type=registry" .
